// One list of upgrade effect descriptions, used by the unlock popup and the Developments page.
// Whole percentages stay whole (15), fractions show properly (2.5 rather than 3) and floating point noise is removed
const pct = v => +(v * 100).toFixed(1)

export const EFFECT_DESCRIPTIONS = {
    foodIncome: (v) => `+${pct(v)}% income from Food developments`,
    recreationIncome: (v) => `+${pct(v)}% income from Recreation developments`,
    shoppingIncome: (v) => `+${pct(v)}% income from Shopping developments`,
    serviceIncome: (v) => `+${pct(v)}% income from Service developments`,
    developmentBoost: (v) => `+${pct(v)}% income from all developments`,
    prestigePoints: (v) => `Rewards ${v} Prestige Points`,
    connectionBoost: (v) => `+${pct(v)}% income from all city connections`,
    workClickBonus: () => `+45% Work click earnings`,
    offlineCapExtension: () => `+24 hours offline earnings cap`,
    developmentDiscount: (v) => `-${pct(v)}% development construction cost`,
    delayCompensationReduction: (v) => `-${pct(v)}% delay compensation cost`,
    delayRepCostReduction: (v) => `-${v} Reputation when ignoring delays`,
    bonusDurationExtension: (v) => `Bonus events last ${pct(v)}% longer`,
    farewellWindowExtension: (v) => `+${v} minutes farewell window`,
    farewellRepDoubled: () => `Reputation from farewells doubled`,
    negativeEventReduction: (v) => `Negative events ${pct(v)}% less likely`,
    workRepChanceDouble: () => `Double chance of Reputation from Work`,
    workRepChanceTriple: () => `Triple chance of Reputation from Work`,
    continentExpansionBoost: (v) => `+${pct(v)}% city income per unique continent connected`,
    countryExpansionBoost: (v) => `+${pct(v)}% city income per unique country connected`,
    southernHemisphereBoost: (v) => `+${pct(v)}% from southern hemisphere cities`,
    arcticBoost: (v) => `+${pct(v)}% income from Arctic cities`,
    continentBoost: (v) => `+${pct(v)}% income from cities on this continent`,
    countryAdvertisingBoost: (v) => `+${pct(v)}% income from cities in this country`,
    localCountryBoost: () => `Bonus income from cities in your home country`,
    dailyLoginMultiplier: () => 'Doubles your daily login cash bonus',
    progressRewardBoost: () => 'Doubles the cash and Reputation rewards from city and country discoveries on the Progress page',
    terminalAgeBoost: () => '+1% to all income per 10 days active; grows the longer you play',
    seasonBoost: (v, upgrade) => { const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']; const isMonthly = months.some(m => upgrade?.name?.includes(m)); return `+${pct(v)}% income during this ${isMonthly ? 'month' : 'season'}`; },
    rerollRepDiscount: (v) => `-${v} Reputation cost to re-roll cities`,
    freeRerollOnRankUp: () => `One free city re-roll each time you rank up`,
    positiveEventBoost: (v) => `+${pct(v)}% chance of positive events`,
    dailyLoginRep: (v) => `+${v} Reputation every day you log in`,
    freeRepOnRankUp: (v) => `+${v} Reputation each time you rank up`,
    businessWeekBoost: (v) => `+${pct(v)}% earnings Monday to Friday`,
    dailyRepDoubled: () => `Doubles the daily login Reputation (needs Passenger Loyalty Scheme)`,
    equatorBoost: (v) => `+${pct(v)}% income from cities near the equator`,
    infrastructureDevBoost: (v) => `+${pct(v)}% development income per Infrastructure item owned`,
    enterpriseDevBoost: (v) => `+${pct(v)}% development income per Enterprise item owned`,
    serviceDevBoost: (v) => `+${pct(v)}% development income per Service item owned`,
    devContinentBoost: (v) => `+${pct(v)}% development income per unique continent connected`,
    morningBoost: (v) => `+${pct(v)}% earnings between 6am and 12pm`,
    afternoonBoost: (v) => `+${pct(v)}% earnings between 12pm and 6pm`,
    eveningBoost: (v) => `+${pct(v)}% earnings between 6pm and 10pm`,
    nightBoost: (v) => `+${pct(v)}% earnings between 10pm and 6am`,
    weekendBoost: (v) => `+${pct(v)}% earnings on weekends`,
    smallCityBoost: (v) => `+${pct(v)}% income from cities under 100,000 population`,
    christmasBoost: () => `+100% all earnings on Christmas Day`,
    valentinesBoost: () => `+100% all earnings on Valentine's Day`,
    halloweenBoost: () => `+100% all earnings on Halloween`,
    fourthOfJulyBoost: () => `+100% all earnings on 4th of July`,
    easterBoost: () => `+100% all earnings on Easter Sunday`,
    newYearsBoost: () => `+100% all earnings on New Year's Day`,
    skilledNegotiationTeams: () => `Guaranteed at least Tier 2 city on each rank up`,
    personalImageBranding: (v) => `Earn ${pct(v)}% of a city's daily income when giving a farewell`,
    firstFarewellOfDayDouble: () => `First farewell of the day earns double Reputation`,
    developmentUpgradeDiscount: (v) => `-${pct(v)}% development upgrade cost`,
}